/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laptop;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author Faris Rizky R
 */
public class FrameReadLaptop extends javax.swing.JFrame {

    /**
     * Creates new form FrameReadLaptop
     */
    private final DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nama Laptop", "Kategori OS"}, 0);

    public FrameReadLaptop() {
        initComponents();

        KategoriLaptop();
        // Set model dan disable kolom ID
        TableLaptop.setModel(model);
        TableLaptop.getColumnModel().getColumn(0).setMinWidth(0);
        TableLaptop.getColumnModel().getColumn(0).setMaxWidth(0);
        TableLaptop.getColumnModel().getColumn(0).setWidth(0);

        ReadLaptop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FormSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        FilterLaptopBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableLaptop = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Laptopers");

        FormSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        FilterLaptopBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterLaptopBoxActionPerformed(evt);
            }
        });

        TableLaptop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nama", "Kategori OS"
            }
        ));
        jScrollPane1.setViewportView(TableLaptop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(FormSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(FilterLaptopBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(FilterLaptopBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FormSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // Menangkap nilai pencarian dari FormSearch
        String searchLaptop = FormSearch.getText();

        try {
            model.setRowCount(0); // Hapus semua data dari tabel
            Connection conn = new Koneksi().getConnection();

            // Query untuk pencarian berdasarkan nama laptop
            String query = "SELECT l.id, l.nama, k.kategori_os FROM laptop l JOIN kategori k ON l.os = k.id WHERE l.nama LIKE ? ORDER BY l.id DESC";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, "%" + searchLaptop + "%");

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                int idLaptop = rs.getInt("id");
                String namaLaptop = rs.getString("nama");
                String kategoriOS = rs.getString("kategori_os");
                model.addRow(new Object[]{idLaptop, namaLaptop, kategoriOS});
            }

            conn.close();
        } catch (SQLException e) {
            System.err.println("Gagal memuat data laptop: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void FilterLaptopBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterLaptopBoxActionPerformed
        String selectedCategory = (String) FilterLaptopBox.getSelectedItem();
        System.out.println(FilterLaptopBox.getSelectedItem());
        if (selectedCategory.equals("Pilih Kategori")) {
            ReadLaptop();
        } else {
            model.setRowCount(0); // Hapus semua data dari tabel
            try {
                Connection conn = new Koneksi().getConnection();
                String query = "SELECT l.id, l.nama, k.kategori_os FROM laptop l JOIN kategori k ON l.os = k.id WHERE k.kategori_os = ? ORDER BY l.id DESC";
                java.sql.PreparedStatement ps = conn.prepareStatement(query);
                ps.setString(1, selectedCategory);

                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    int idLaptop = rs.getInt("id");
                    String namaLaptop = rs.getString("nama");
                    String kategoriOS = rs.getString("kategori_os");
                    model.addRow(new Object[]{idLaptop, namaLaptop, kategoriOS});
                }

                conn.close();
            } catch (SQLException e) {
                System.err.println("Gagal memuat data laptop berdasarkan kategori: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_FilterLaptopBoxActionPerformed

    private void ReadLaptop() {
        try {
            Connection conn = new Koneksi().getConnection();
            String query = "SELECT l.id, l.nama, k.kategori_os FROM laptop l JOIN kategori k ON l.os = k.id ORDER BY l.id DESC";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            model.setRowCount(0); // Hapus semua data dari tabel

            while (rs.next()) {
                int idLaptop = rs.getInt("id");
                String namaLaptop = rs.getString("nama");
                String kategoriOS = rs.getString("kategori_os");
                model.addRow(new Object[]{idLaptop, namaLaptop, kategoriOS});
            }

            conn.close();
        } catch (SQLException e) {
            System.err.println("Gagal memuat data laptop: " + e.getMessage());
        }
    }

    private void KategoriLaptop() {
        FilterLaptopBox.addItem("Pilih Kategori");

        try {
            Connection conn = new Koneksi().getConnection();
            String query = "SELECT kategori_os FROM kategori";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                FilterLaptopBox.addItem(rs.getString("kategori_os"));
            }

            conn.close();
        } catch (SQLException e) {
            System.err.println("Gagal memuat kategori: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameReadLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameReadLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameReadLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameReadLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameReadLaptop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FilterLaptopBox;
    private javax.swing.JTextField FormSearch;
    private javax.swing.JTable TableLaptop;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
