/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laptop;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.sql.PreparedStatement;

/**
 *
 * @author faiqa
 */
public class FrameTransaksi extends javax.swing.JFrame {

    private final DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nama Laptop", "Tanggal Sewa", "Tanggal Pengembalian", "Harga Sewa", "ID Laptop"}, 0);
    private final DefaultComboBoxModel<ManageLaptop> modelList = new DefaultComboBoxModel<>();
    private Transaksi transaksi;
    private static final Koneksi k = new Koneksi();
    private int selectedIdTransaksi = 0;
    private int selectedIdLaptop = 0;
    private String selectNamaLaptop = "";
    private Integer laptopId = 0;
    private ManageLaptop pilihLaptop = new ManageLaptop(0, "Pilih Laptop");

    /**
     * Creates new form FrameTransaksi
     */
    public FrameTransaksi() {
        initComponents();

        listLaptop.setModel(modelList);
        //listLaptop.getModel().getElementAt(0);
        tableTransaksi.setModel(model);
        tableTransaksi.getColumnModel().getColumn(0).setMinWidth(0);
        tableTransaksi.getColumnModel().getColumn(0).setMaxWidth(0);
        tableTransaksi.getColumnModel().getColumn(0).setWidth(0);
        ReadTransaksi();
        DaftarLaptop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputTanggalSewa = new com.toedter.calendar.JDateChooser();
        inputTanggalKembali = new com.toedter.calendar.JDateChooser();
        listLaptop = new javax.swing.JComboBox<>(modelList);
        createButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Transaksi");

        jLabel2.setText("Tanggal Sewa");

        jLabel3.setText("Tanggal Kembali");

        jLabel4.setText("Laptop");

        listLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listLaptopActionPerformed(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Laptop", "Tanggal Sewa", "Tanggal Kembali", "Total Harga", "ID Laptop"
            }
        ));
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(241, 241, 241)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(listLaptop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inputTanggalKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inputTanggalSewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 159, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(inputTanggalSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(inputTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(listLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        ManageLaptop selectedItem = (ManageLaptop) listLaptop.getSelectedItem();
        if (selectedItem != null && selectedItem != pilihLaptop) {
            try {
                com.toedter.calendar.JDateChooser tanggalSewa = inputTanggalSewa;
                com.toedter.calendar.JDateChooser tanggalKembali = inputTanggalKembali;

                transaksi = new Transaksi(selectedIdTransaksi, tanggalSewa, tanggalKembali, selectedItem.getId());
                try {
                    Connection conn = k.getConnection();
                    String queryLama = """
                                UPDATE laptop
                                SET status = ?
                                WHERE id = ?
                            """;

                    PreparedStatement pslama = conn.prepareStatement(queryLama);

                    pslama.setInt(1, 1);
                    pslama.setInt(2, selectedIdLaptop);

                    pslama.executeUpdate();
                    model.setRowCount(0);  // Menghapus semua baris dari model
                    ReadTransaksi();  // Memuat ulang data transaksi ke dalam tabel
                } catch (SQLException e) {
                    System.out.println("Gagal update status laptop: " + e.getMessage());
                }
                if (transaksi.updateTransaksi()) {
                    //transaksi.updateTransaksi();
                    try {
                        Connection conn = k.getConnection();
                        String query = """
                                    UPDATE laptop
                                    SET status = ?
                                    WHERE id = ?
                                """;

                        PreparedStatement ps = conn.prepareStatement(query);

                        ps.setInt(1, 2);
                        ps.setInt(2, transaksi.getIdLaptop());

                        ps.executeUpdate();


                        model.setRowCount(0);  // Menghapus semua baris dari model
                        ReadTransaksi();  // Memuat ulang data transaksi ke dalam tabel
                        //listLaptop.removeAllItems();;
                        modelList.removeAllElements();
                        DaftarLaptop();
                    } catch (SQLException e) {
                        System.out.println("Gagal update status laptop: " + e.getMessage());
                    }
                    System.out.println("Transaksi berhasil disimpan!");
                } else {
                    System.err.println("Transaksi gagal disimpan!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Tidak ada laptop yang dipilih!");
                System.err.println("Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        //String selectedItem = (String) listLaptop.getSelectedItem();
        ManageLaptop selectedItem = (ManageLaptop) listLaptop.getSelectedItem();
        if (selectedItem != null && selectedItem != pilihLaptop) {
            try {
                com.toedter.calendar.JDateChooser tanggalSewa = inputTanggalSewa;
                com.toedter.calendar.JDateChooser tanggalKembali = inputTanggalKembali;
                //int laptop = (Integer) listLaptop.getClientProperty(selectNamaLaptop);

                transaksi = new Transaksi(0, tanggalSewa, tanggalKembali, selectedItem.getId());

                if (transaksi.insertTransaksi()) {
                    try {
                        Connection conn = k.getConnection();
                        String query = """
                                    UPDATE laptop
                                    SET status = ?
                                    WHERE id = ?
                                """;

                        PreparedStatement ps = conn.prepareStatement(query);

                        ps.setInt(1, 2);
                        ps.setInt(2, transaksi.getIdLaptop());

                        ps.executeUpdate();
                        model.setRowCount(0);  // Menghapus semua baris dari model
                        ReadTransaksi();  // Memuat ulang data transaksi ke dalam tabel
                        //modelList.removeAllElements();
                        //listLaptop.removeAllItems();
                        DaftarLaptop();
                        System.out.println("Transaksi berhasil disimpan!");
                    } catch (SQLException e) {
                        System.out.println("Gagal update status laptop: " + e.getMessage());
                    }
                } else {
                    System.err.println("Transaksi gagal disimpan!");
                }
            } catch (Exception e) {
                System.err.println("Error a: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada laptop yang dipilih!");
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        transaksi.setId(selectedIdTransaksi);

        if (transaksi.deleteTransaksi()) {
            try {
                Connection conn = k.getConnection();
                String query = """
                    UPDATE laptop
                    SET status = ?
                    WHERE id = ?
                """;

                PreparedStatement ps = conn.prepareStatement(query);

                ps.setInt(1, 3);
                ps.setInt(2, selectedIdLaptop);

                ps.executeUpdate();

                System.out.println("Transaksi berhasil dihapus!");
                model.setRowCount(0);  // Menghapus semua baris dari model
                ReadTransaksi();  // Memuat ulang data transaksi ke dalam tabel
                DaftarLaptop();
            } catch (SQLException e) {
                System.out.println("Gagal update status laptop: " + e.getMessage());
            }
        } else {
            System.out.println("Gagal menghapus transaksi.");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void listLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listLaptopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listLaptopActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        // Untuk Get ID Transaksi
        int row = tableTransaksi.getSelectedRow();
        Object selectedIdTransaksiObject = tableTransaksi.getValueAt(row, 0);
        selectedIdTransaksi = (int) selectedIdTransaksiObject;
        System.out.println(selectedIdTransaksi);

        // Untuk Get ID Laptop
        Object selectedIdLaptopObject = tableTransaksi.getValueAt(row, 5);
        selectedIdLaptop = (int) selectedIdLaptopObject;
        System.out.println(selectedIdLaptop);

        String namaLaptop = (String) tableTransaksi.getValueAt(row, 1); // Nama Laptop
        Date tanggalSewa = (Date) tableTransaksi.getValueAt(row, 2); // Tanggal Sewa
        Date tanggalPengembalian = (Date) tableTransaksi.getValueAt(row, 3); // Tanggal Pengembalian

        System.out.println(namaLaptop);

        // Tampilkan data ke form
//        listLaptop.setSelectedItem(namaLaptop);

        // Tetapkan nilai ke JDateChooser untuk tanggal sewa
        inputTanggalSewa.setDate(tanggalSewa);
        inputTanggalKembali.setDate(tanggalPengembalian);
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void ReadTransaksi() {
        try {
            Connection conn = new Koneksi().getConnection();
            String query = "SELECT t.id, l.nama, t.tanggal_sewa, t.tanggal_kembali, t.total_harga, l.id FROM transaksi t JOIN laptop l on t.id_laptop = l.id";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            model.setRowCount(0); // Hapus semua data dari tabel

            while (rs.next()) {
                int idTransaksi = rs.getInt("t.id");
                String namaLaptop = rs.getString("l.nama");
                Date tanggalSewa = rs.getDate("t.tanggal_sewa");
                Date tanggalKembali = rs.getDate("t.tanggal_kembali");
                int hargaTotal = rs.getInt("t.total_harga");
                int idLaptop = rs.getInt("l.id");
                model.addRow(new Object[]{idTransaksi, namaLaptop, tanggalSewa, tanggalKembali, hargaTotal, idLaptop});
            }
            conn.close();
        } catch (SQLException e) {
            System.err.println("Gagal memuat data laptop: " + e.getMessage());
        }
    }

    private void DaftarLaptop() {
        //listLaptop.removeAllItems();
        //listLaptop.addItem("Pilih Laptop");
        modelList.removeAllElements();
        modelList.addElement(pilihLaptop);
        //modelList.addElement();
        //listLaptop.addItem("Pilih Laptop");

        try {
            Connection conn = new Koneksi().getConnection();
            String query = "SELECT id, nama FROM laptop WHERE status = 1";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("nama");
                modelList.addElement(new ManageLaptop(id, nama));
                //listLaptop.addItem(nama);
                //listLaptop.putClientProperty(nama, id);
            }

        } catch (SQLException e) {
            System.err.println("Gagal memuat kategori: " + e.getMessage());
        }

        listLaptop.addActionListener(evt -> {
            ManageLaptop selectedLaptop = (ManageLaptop) modelList.getSelectedItem();
            if (selectedLaptop != null) {
                String selectNamaLaptop = selectedLaptop.getNama();
                int laptopId = selectedLaptop.getId();
                System.out.println("Item selected in combobox: " + selectNamaLaptop);
                System.out.println(laptopId);
            }
            //selectNamaLaptop = (String) modelList.getSelectedItem();
            //laptopId = (Integer) listLaptop.getClientProperty(selectNamaLaptop);

            //String selectedItem = (String) listLaptop.getSelectedItem();

        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteButton;
    private com.toedter.calendar.JDateChooser inputTanggalKembali;
    private com.toedter.calendar.JDateChooser inputTanggalSewa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<ManageLaptop> listLaptop;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
